# Generated by Django 3.1.2 on 2020-12-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(max_length=20, verbose_name='IP Address')),
                ('valid', models.BooleanField(verbose_name='Allowed')),
            ],
        ),
    ]
